routes/web.php
<?php

use App\Http\Controllers\BehavioralPatternsController;
use App\Http\Controllers\CreationalPatternsController;
use App\Http\Controllers\DiggingDeeperController;
use App\Http\Controllers\StructuralPatternsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RestController;
use App\Http\Controllers\FundamentalPatternsControllerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::resource('rest', RestController::class)->names('rest');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['role:admin'])->prefix('super-admin')->group( function () {
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin.home.index');
    Route::resource('book', App\Http\Controllers\Admin\BookController::class)->names('admin.home.book');
});

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'fundamentals'], function() {
    Route::get('property-container', [FundamentalPatternsControllerController::class, 'propertyContainer'])->name('propertyContainer');
    Route::get('delegation', [FundamentalPatternsControllerController::class, 'delegation'])->name('delegation');
    Route::get('event-channel', [FundamentalPatternsControllerController::class, 'eventChannel'])->name('eventChannel');
    Route::get('interface-pattern', [FundamentalPatternsControllerController::class, 'interfacePattern'])->name('interfacePattern');
});

Route::group(['prefix' => 'creational'], function() {
    Route::get('abstract-factory', [CreationalPatternsController::class, 'abstractFactory'])->name('abstractFactory');
    Route::get('factory-method', [CreationalPatternsController::class, 'factoryMethod'])->name('factoryMethod');
    Route::get('static-factory', [CreationalPatternsController::class, 'staticFactory'])->name('staticFactory');
    Route::get('simple-factory', [CreationalPatternsController::class, 'simpleFactory'])->name('simpleFactory');
    Route::get('singleton', [CreationalPatternsController::class, 'singleton'])->name('singleton');
    Route::get('multiton', [CreationalPatternsController::class, 'multiton'])->name('multiton');
    Route::get('builder', [CreationalPatternsController::class, 'builder'])->name('builder');
    Route::get('lazy-initialization', [CreationalPatternsController::class, 'lazyInitialization'])->name('lazyInitialization');
    Route::get('prototype', [CreationalPatternsController::class, 'prototype'])->name('prototype');
    Route::get('object-pool', [CreationalPatternsController::class, 'objectPool'])->name('objectPool');
});
Route::group(['prefix' => 'structural'], function() {
    Route::get('adapter', [StructuralPatternsController::class, 'adapter'])->name('adapter');
    Route::get('facade', [StructuralPatternsController::class, 'facade'])->name('facade');
});

Route::group(['prefix' => 'behavioral'], function() {
    Route::get('strategy', [BehavioralPatternsController::class, 'strategy'])->name('strategy');
});

Route::group(['prefix' => 'digging_deeper'], function() {
    Route::get('collections', [DiggingDeeperController::class, 'collections'])->name('digging_deeper.collections');
    Route::get('prepare-catalog', [DiggingDeeperController::class, 'prepareCatalog'])->name('digging_deeper.prepareCatalog');
});

Route::group(['namespace' => 'App\Http\Controllers\Book', 'prefix' => 'books'], function() {
    Route::resource('index', 'BookController');
});

Route::get('admin/books/pages/{page}/restore', [App\Http\Controllers\Book\Admin\PageController::class, 'restore'])->name('admin.pages.model.restore');
Route::group(['namespace' => 'App\Http\Controllers\Book\Admin', 'prefix' => 'admin/books'], function() {
    $methods = ['index', 'show', 'edit', 'update', 'create', 'store', 'destroy'];
    Route::resource('item', 'BookController')
        ->only($methods)
        ->names('admin.books.model');

    Route::resource('pages', 'PageController')
        ->except(['show'])
        ->names('admin.pages.model');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\User;

/**
 * Class Book
 * @package App\Models
 *
 * @property User $user
 * @property User $authorBook
 * @property string $title
 * @property string $slug
 * @property string $description
 * @property integer $user_id
 */
class Book extends Model
{
    use HasFactory, SoftDeletes;

    const UNKNOWN_USER = 1;

    protected $fillable = ['title', 'slug', 'user_id', 'description',];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function authorBook()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Repositories\BookRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BookController extends Controller
{
    /**
     * @var BookRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $bookRepository;

    public function __construct()
    {
        $this->bookRepository = app(BookRepository::class);
    }
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $paginator = $this->bookRepository->getAllWithPaginate(10);

        return view('admin.home.books.index', ['paginator' => $paginator]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('admin.home.books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $data = $request->input();
        if (empty($data['slug'])) {
            $data['slug'] = Str::of($data['title'])->slug();
        }
        $data['user_id'] = \Auth::user()->id;

        $item = (new Book())->create($data);

        if ($item) {
            return redirect()
                ->route('admin.home.book.index')
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Сохранение не удалось'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Page;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $pages_count = Page::all()->count();

        return view('admin.home.index', ['pages_count' => $pages_count]);
    }
}

app/Http/Controllers/Book/Admin/BaseController.php
<?php

namespace App\Http\Controllers\Book\Admin;

use App\Http\Controllers\Book\BaseController as GuestBaseController;

abstract class BaseController extends GuestBaseController
{
    //
    public function __construct()
    {

    }
}

app/Http/Controllers/Book/Admin/BookController.php
<?php

namespace App\Http\Controllers\Book\Admin;

use App\Http\Requests\BookUpdateRequest;
use App\Models\Book;
use App\Repositories\BookRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BookController extends BaseController
{
    /**
     * @var BookRepository
     */
    private $bookRepository;

    /**
     * @var UserRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $userRepository;

    public function __construct()
    {
        parent::__construct();
        $this->bookRepository = app(BookRepository::class);
        $this->userRepository = app(UserRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        // $paginator = Book::paginate(5);
        $paginator = $this->bookRepository->getAllWithPaginate(5);
        return view('admin.books.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     * @param UserRepository $userRepository
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create(UserRepository $userRepository)
    {
        $item = new Book();
        $usersList = $this->userRepository->getForComboBox();

        return view('admin.books.edit', compact('item', 'usersList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(BookUpdateRequest $request)
    {
        $data = $request->input();
        if (empty($data['slug'])) {
            $data['slug'] = Str::of($data['title'])->slug();
        }

        $item = (new Book())->create($data);

        if ($item) {
            return redirect()
                ->route('admin.books.model.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Сохранение не удалось'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd(__METHOD__);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param BookRepository $bookRepository
     * @param UserRepository $userRepository
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id, BookRepository $bookRepository, UserRepository $userRepository)
    {
        /*$item = Book::findOrFail($id);
        $userList = Book::all();*/

        $item = $this->bookRepository->getEdit($id);
        if (empty($item)) {
            abort(404);
        }
        $usersList = $this->userRepository->getForComboBox();

        return view('admin.books.edit', compact('item', 'usersList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(BookUpdateRequest $request, $id)
    {
        // $item = Book::find($id);
        $item = $this->bookRepository->getEdit($id);
        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "Запись с ИД: {$id} не найдена"])
                ->withInput();
        }

        $data = $request->all(); # analog -> $request->input();
        /* replace to observer
         * if (empty($data['slug'])) {
            $data['slug'] = Str::of($data['title'])->slug();
        }*/
        $result = $item->fill($data)->save(); # or $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('admin.books.model.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Сохранение не удалось'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd(__METHOD__);
    }
}

app/Http/Controllers/Book/BaseController.php
<?php

namespace App\Http\Controllers\Book;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

abstract class BaseController extends Controller
{
    //
}

app/Http/Controllers/Book/BookController.php
<?php

namespace App\Http\Controllers\Book;

use App\Models\Book;
use Illuminate\Http\Request;

class BookController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $items = Book::all();

        return view('books.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/home/books/create.blade.php
@extends('layouts.admin')

@section('title', 'Добавление книги')

@section('content')

    @include('admin.home.books.includes.result_messages')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="card card-primary">
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{ route('admin.home.book.store') }}" method="post">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="title">Название</label>
                                <input name="title" type="text" class="form-control" id="title" placeholder="Введите название" required>
                            </div>
                            <div class="form-group">
                                <label for="description">Описание</label>
                                <textarea name="description" type="description" class="form-control tiny-editor" id="description" placeholder="Введите описание"></textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/home/books/index.blade.php
@extends('layouts.admin')

@section('title', 'Главная')

@section('content')

    @include('admin.home.books.includes.result_messages')

    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Название
                        </th>
                        <th>
                            Управление
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($paginator as $item)
                        @php /** @var App\Models\Book $item */ @endphp
                        @php /** @var Illuminate\Pagination\Paginator $paginator */ @endphp
                        <tr>
                            <td>
                                #
                            </td>
                            <td>
                                <a>
                                    {{ $item->title }}
                                </a>
                                <br/>
                                <small>
                                    {{ $item->created_at }}
                                </small>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="#">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="#">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <a class="btn btn-danger btn-sm" href="#">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{ $paginator->links() }}
                        </div>
                    </div>
                </div>
            </div>
        @endif

    </section>
@endsection